---
title: "DATA 607 project01:Chess Tournament Data Analysis"
author: "Lionel jr. desroses"
output: html_document
editor: visual
format:
  html:
    theme: cosmo
    toc: true
    toc-location: left
    toc-depth: 3
    code-fold: true
    code-summary: "Show code"
    code-tools: true
    df-print: paged
    smooth-scroll: true
    embed-resources: true
date: "2026-09-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Introduction
This project is about transforming a semi-structured chess tournament text file into a clean and organized dataset that can be analyzed and exported as a CSV file. The tournament file contains information about each player, including their name, state, total points earned, pre-tournament rating, and the opponents they faced throughout the tournament.The goal of the project is to extract the required information for each player and calculate the average pre-tournament rating of all opponents they played against. Since the opponent ratings are not directly provided with each game result, additional processing is required to identify each opponent and retrieve their corresponding pre-tournament rating from the tournament data.Although the source file follows a consistent format, the data is spread across multiple lines and contains game results embedded within text fields. Therefore, much of the work in this project involves parsing, cleaning, and restructuring the data before performing the final calculations.

## Approach

My approach for this project is to treat the tournament data similarly to a relational database. First, I will create a player table containing one record per player, including their player number, name, state, total points, pre-tournament rating, and opponent numbers for each round.Then I would generated a game table by iterating through the round information for each player and extracting valid opponent numbers. This produced a table containing the player number, round number, and opponent number for every recorded game. Rounds containing no number or played game value were excluded because they do not represent games against actual opponents.
Once the game table is created, opponent numbers were matched back to the player table to retrieve the opponents' pre-tournament ratings. These ratings is the averaged for each player to produce the required average opponent rating value.

One of the main challenges in this project would be that the opponent ratings were not directly available within the game results. Instead, each opponent had to be identified by player number and then matched back to the corresponding player record to obtain their pre-tournament rating.And because the source file is not stored in a traditional tabular format, multiple parsing and data-cleaning steps were required before the information could be transformed into a structured dataset suitable for analysis.



